# SPDX-License-Identifier: MIT

language: c

compiler:
  - gcc
matrix:
  include:
    - os: linux
      before_install:
        - docker pull debian:latest
        - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/travis -w /travis -td debian:latest /bin/bash
      install:
        - docker exec -ti travis-ci bash -c "apt-get update"
        - docker exec -ti travis-ci bash -c "apt-get install -y build-essential git libhdf5-dev"
    - os: linux
      before_install:
        - docker pull debian:testing
        - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/travis -w /travis -td debian:testing /bin/bash
      install:
        - docker exec -ti travis-ci bash -c "apt-get update"
        - docker exec -ti travis-ci bash -c "apt-get install -y build-essential git libhdf5-dev"
    - os: linux
      before_install:
        - docker pull fedora:latest
        - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/travis -w /travis -td fedora:latest /bin/bash
      install:
        - docker exec -ti travis-ci bash -c "dnf -y update"
        - docker exec -ti travis-ci bash -c "dnf -y install @development-tools git hdf5-devel redhat-rpm-config"
# Adding jobs for ppc64le architecture
    - os: linux
      arch: ppc64le
      before_install:
        - docker pull debian:latest
        - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/travis -w /travis -td debian:latest /bin/bash
      install:
        - docker exec -i travis-ci bash -c "sudo apt-get update"
        - docker exec -i travis-ci bash -c "sudo apt-get install -y build-essential git libhdf5-dev"
    - os: linux
      arch: ppc64le
      before_install:
        - docker pull debian:testing
        - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/travis -w /travis -td debian:testing /bin/bash
      install:
        - docker exec -i travis-ci bash -c "sudo apt-get update"
        - docker exec -i travis-ci bash -c "sudo apt-get install -y build-essential git libhdf5-dev"
    - os: linux
      arch: ppc64le
      before_install:
        - docker pull fedora:latest
        - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/travis -w /travis -td fedora:latest /bin/bash
      install:
        - docker exec -i travis-ci bash -c "dnf -y update"
        - docker exec -i travis-ci bash -c "dnf -y install @development-tools git hdf5-devel redhat-rpm-config" 
script:
  - docker exec -ti travis-ci bash -c "CC=$CC CXX=$CXX make"
after_script:
  - docker stop travis-ci
